name: Build Docker Image

on:
  push:
    branches:
      - '*'  # Trigger build on push to the main branch
  pull_request:
    branches:
      - '*'  # Trigger build on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for advanced build features

    - name: Cache Docker layers
      uses: actions/cache@v4  # Cache Docker layers to speed up subsequent builds
      with:
        path: /tmp/.buildx-cache  # Define the cache path
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Build Docker image
      run: |
        docker build --file Dockerfile --tag myapp:${{ github.sha }} .  # Build Docker image with a tag of the current commit SHA

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Log in to Docker Hub (or other Docker registries)
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret

    - name: Push Docker image to Docker Hub
      run: |
        docker tag myapp:${{ github.sha }} myusername/myapp:${{ github.sha }}  # Tag the image
        docker push myusername/myapp:${{ github.sha }}  # Push the image to Docker Hub
      if: success()  # Push image only if the build was successful

    - name: Clean up Docker images
      run: |
        docker rmi myapp:${{ github.sha }}  # Remove the local image after push
